export type CanonicalMediaType = "movie" | "tv" | "anime" | "arc";

export type CanonicalEntry = {
  id: string;
  title: string;
  aliases: string[];
  universe: string;
  mediaType: CanonicalMediaType;
  releaseYear?: string;
  chronologyIndex: number;
  releaseIndex: number;
  canonStatus: "canon" | "legacy-canon" | "optional-canon";
  requiredBefore: string[];
  optionalBefore: string[];
  emotionalContext: string;
  continuityRelevance: string;
  importanceScore: number;
  tmdbQuery?: string;
};

export type CanonicalUniverse = {
  id: string;
  name: string;
  aliases: string[];
  entries: CanonicalEntry[];
};

const marvelEntries: CanonicalEntry[] = [
  {
    id: "the-avengers",
    title: "The Avengers",
    aliases: ["avengers", "marvel avengers", "avengers 2012"],
    universe: "Marvel",
    mediaType: "movie",
    releaseYear: "2012",
    chronologyIndex: 80,
    releaseIndex: 80,
    canonStatus: "canon",
    requiredBefore: [],
    optionalBefore: [],
    emotionalContext: "team formation and first shared sacrifice",
    continuityRelevance: "unites the core Avengers and establishes the team dynamic that Endgame resolves",
    importanceScore: 96,
    tmdbQuery: "The Avengers",
  },
  {
    id: "avengers-age-of-ultron",
    title: "Avengers: Age of Ultron",
    aliases: ["age of ultron", "avengers ultron", "ultron"],
    universe: "Marvel",
    mediaType: "movie",
    releaseYear: "2015",
    chronologyIndex: 120,
    releaseIndex: 120,
    canonStatus: "canon",
    requiredBefore: ["the-avengers"],
    optionalBefore: [],
    emotionalContext: "creation anxiety and fractured trust",
    continuityRelevance: "pushes the Avengers toward internal division and introduces consequences that echo into later team stories",
    importanceScore: 90,
    tmdbQuery: "Avengers: Age of Ultron",
  },
  {
    id: "daredevil-s1",
    title: "Daredevil Season 1",
    aliases: ["daredevil", "daredevil s1", "matt murdock season 1"],
    universe: "Marvel",
    mediaType: "tv",
    releaseYear: "2015",
    chronologyIndex: 100,
    releaseIndex: 101,
    canonStatus: "canon",
    requiredBefore: [],
    optionalBefore: [],
    emotionalContext: "origin and moral code",
    continuityRelevance: "establishes Matt Murdock, Fisk, Hell's Kitchen, and the street-level tone",
    importanceScore: 98,
    tmdbQuery: "Marvel's Daredevil",
  },
  {
    id: "daredevil-s2",
    title: "Daredevil Season 2",
    aliases: ["daredevil s2", "punisher daredevil", "elektra daredevil"],
    universe: "Marvel",
    mediaType: "tv",
    releaseYear: "2016",
    chronologyIndex: 125,
    releaseIndex: 102,
    canonStatus: "canon",
    requiredBefore: ["daredevil-s1"],
    optionalBefore: [],
    emotionalContext: "vigilante pressure and fractured loyalty",
    continuityRelevance: "introduces Frank Castle and Elektra while testing Matt's limits",
    importanceScore: 94,
    tmdbQuery: "Marvel's Daredevil",
  },
  {
    id: "the-defenders",
    title: "The Defenders",
    aliases: ["defenders", "marvel defenders"],
    universe: "Marvel",
    mediaType: "tv",
    releaseYear: "2017",
    chronologyIndex: 165,
    releaseIndex: 103,
    canonStatus: "canon",
    requiredBefore: ["daredevil-s2"],
    optionalBefore: ["jessica-jones-s1", "luke-cage-s1", "iron-fist-s1"],
    emotionalContext: "team collision and sacrifice",
    continuityRelevance: "bridges Matt and Elektra's unresolved arc into Season 3",
    importanceScore: 90,
    tmdbQuery: "Marvel's The Defenders",
  },
  {
    id: "daredevil-s3",
    title: "Daredevil Season 3",
    aliases: ["daredevil s3", "daredevil season three", "bullseye daredevil"],
    universe: "Marvel",
    mediaType: "tv",
    releaseYear: "2018",
    chronologyIndex: 175,
    releaseIndex: 104,
    canonStatus: "canon",
    requiredBefore: ["the-defenders"],
    optionalBefore: [],
    emotionalContext: "faith crisis and identity collapse",
    continuityRelevance: "defines the Matt/Fisk rivalry most directly before Born Again",
    importanceScore: 99,
    tmdbQuery: "Marvel's Daredevil",
  },
  {
    id: "spider-man-no-way-home",
    title: "Spider-Man: No Way Home",
    aliases: ["spider man no way", "no way home", "spiderman no way home", "nwh"],
    universe: "Marvel",
    mediaType: "movie",
    releaseYear: "2021",
    chronologyIndex: 210,
    releaseIndex: 210,
    canonStatus: "canon",
    requiredBefore: [],
    optionalBefore: ["spider-man-homecoming", "spider-man-far-from-home"],
    emotionalContext: "public identity fallout",
    continuityRelevance: "reintroduces Matt Murdock into the wider MCU context",
    importanceScore: 78,
    tmdbQuery: "Spider-Man: No Way Home",
  },
  {
    id: "hawkeye",
    title: "Hawkeye",
    aliases: ["hawkeye series", "kingpin hawkeye"],
    universe: "Marvel",
    mediaType: "tv",
    releaseYear: "2021",
    chronologyIndex: 211,
    releaseIndex: 211,
    canonStatus: "optional-canon",
    requiredBefore: [],
    optionalBefore: [],
    emotionalContext: "street-level criminal resurgence",
    continuityRelevance: "shows Wilson Fisk's MCU re-entry",
    importanceScore: 70,
    tmdbQuery: "Hawkeye",
  },
  {
    id: "she-hulk",
    title: "She-Hulk: Attorney at Law",
    aliases: ["she hulk", "she hulk daredevil"],
    universe: "Marvel",
    mediaType: "tv",
    releaseYear: "2022",
    chronologyIndex: 214,
    releaseIndex: 214,
    canonStatus: "optional-canon",
    requiredBefore: [],
    optionalBefore: [],
    emotionalContext: "lighter legal-world cameo",
    continuityRelevance: "shows Matt operating after his Netflix-era trauma",
    importanceScore: 64,
    tmdbQuery: "She-Hulk: Attorney at Law",
  },
  {
    id: "echo",
    title: "Echo",
    aliases: ["echo marvel", "maya lopez", "kingpin echo"],
    universe: "Marvel",
    mediaType: "tv",
    releaseYear: "2024",
    chronologyIndex: 230,
    releaseIndex: 230,
    canonStatus: "canon",
    requiredBefore: ["daredevil-s3"],
    optionalBefore: ["hawkeye"],
    emotionalContext: "Fisk aftermath and street-level power",
    continuityRelevance: "positions Fisk and Maya before the Born Again era",
    importanceScore: 88,
    tmdbQuery: "Echo",
  },
  {
    id: "daredevil-born-again",
    title: "Daredevil: Born Again",
    aliases: ["born again", "daredevil born again", "dd born again"],
    universe: "Marvel",
    mediaType: "tv",
    releaseYear: "2025",
    chronologyIndex: 240,
    releaseIndex: 240,
    canonStatus: "canon",
    requiredBefore: ["daredevil-s1", "daredevil-s2", "the-defenders", "daredevil-s3", "echo"],
    optionalBefore: ["spider-man-no-way-home", "hawkeye", "she-hulk"],
    emotionalContext: "redemption and political-legal collision",
    continuityRelevance: "continues Matt Murdock and Wilson Fisk's central conflict",
    importanceScore: 100,
    tmdbQuery: "Daredevil: Born Again",
  },
  {
    id: "avengers-infinity-war",
    title: "Avengers: Infinity War",
    aliases: ["infinity war", "marvel infinity war"],
    universe: "Marvel",
    mediaType: "movie",
    releaseYear: "2018",
    chronologyIndex: 180,
    releaseIndex: 180,
    canonStatus: "canon",
    requiredBefore: ["the-avengers", "avengers-age-of-ultron", "captain-america-civil-war", "thor-ragnarok"],
    optionalBefore: ["guardians-of-the-galaxy", "black-panther"],
    emotionalContext: "cosmic defeat",
    continuityRelevance: "sets up the emotional and narrative stakes of Endgame",
    importanceScore: 98,
    tmdbQuery: "Avengers: Infinity War",
  },
  {
    id: "avengers-endgame",
    title: "Avengers: Endgame",
    aliases: ["endgame", "marvel endgame", "endgame marvel", "avengers 4"],
    universe: "Marvel",
    mediaType: "movie",
    releaseYear: "2019",
    chronologyIndex: 190,
    releaseIndex: 190,
    canonStatus: "canon",
    requiredBefore: ["the-avengers", "avengers-age-of-ultron", "captain-america-civil-war", "thor-ragnarok", "avengers-infinity-war"],
    optionalBefore: ["guardians-of-the-galaxy", "black-panther", "ant-man-and-the-wasp", "iron-man"],
    emotionalContext: "grief, legacy, and closure",
    continuityRelevance: "concludes the Infinity Saga and resolves the snap",
    importanceScore: 100,
    tmdbQuery: "Avengers: Endgame",
  },
  {
    id: "iron-man",
    title: "Iron Man",
    aliases: ["ironman", "tony stark origin"],
    universe: "Marvel",
    mediaType: "movie",
    releaseYear: "2008",
    chronologyIndex: 10,
    releaseIndex: 10,
    canonStatus: "canon",
    requiredBefore: [],
    optionalBefore: [],
    emotionalContext: "legacy origin",
    continuityRelevance: "starts Tony Stark's MCU arc",
    importanceScore: 82,
    tmdbQuery: "Iron Man",
  },
  {
    id: "captain-america-civil-war",
    title: "Captain America: Civil War",
    aliases: ["civil war", "marvel civil war", "captain america civil war"],
    universe: "Marvel",
    mediaType: "movie",
    releaseYear: "2016",
    chronologyIndex: 150,
    releaseIndex: 150,
    canonStatus: "canon",
    requiredBefore: [],
    optionalBefore: [],
    emotionalContext: "fractured heroes",
    continuityRelevance: "explains Avengers division before Infinity War and Endgame",
    importanceScore: 85,
    tmdbQuery: "Captain America: Civil War",
  },
  {
    id: "thor-ragnarok",
    title: "Thor: Ragnarok",
    aliases: ["ragnarok", "thor ragnarok"],
    universe: "Marvel",
    mediaType: "movie",
    releaseYear: "2017",
    chronologyIndex: 170,
    releaseIndex: 170,
    canonStatus: "canon",
    requiredBefore: [],
    optionalBefore: [],
    emotionalContext: "loss before cosmic war",
    continuityRelevance: "moves Thor and Hulk into the Infinity War opening context",
    importanceScore: 76,
    tmdbQuery: "Thor: Ragnarok",
  },
  {
    id: "spider-man-homecoming",
    title: "Spider-Man: Homecoming",
    aliases: ["homecoming", "spider man homecoming"],
    universe: "Marvel",
    mediaType: "movie",
    releaseYear: "2017",
    chronologyIndex: 160,
    releaseIndex: 160,
    canonStatus: "canon",
    requiredBefore: [],
    optionalBefore: [],
    emotionalContext: "young hero identity",
    continuityRelevance: "starts Peter Parker's solo MCU journey",
    importanceScore: 82,
    tmdbQuery: "Spider-Man: Homecoming",
  },
  {
    id: "guardians-of-the-galaxy",
    title: "Guardians of the Galaxy",
    aliases: ["gotg", "guardians", "guardians galaxy"],
    universe: "Marvel",
    mediaType: "movie",
    releaseYear: "2014",
    chronologyIndex: 90,
    releaseIndex: 110,
    canonStatus: "optional-canon",
    requiredBefore: [],
    optionalBefore: [],
    emotionalContext: "found family and cosmic misfits",
    continuityRelevance: "introduces the cosmic ensemble and Infinity Stone context that enriches Infinity War",
    importanceScore: 74,
    tmdbQuery: "Guardians of the Galaxy",
  },
  {
    id: "black-panther",
    title: "Black Panther",
    aliases: ["wakanda", "black panther marvel"],
    universe: "Marvel",
    mediaType: "movie",
    releaseYear: "2018",
    chronologyIndex: 175,
    releaseIndex: 175,
    canonStatus: "optional-canon",
    requiredBefore: ["captain-america-civil-war"],
    optionalBefore: [],
    emotionalContext: "sovereignty and inherited duty",
    continuityRelevance: "adds Wakanda context before the Infinity War and Endgame battles",
    importanceScore: 72,
    tmdbQuery: "Black Panther",
  },
  {
    id: "ant-man-and-the-wasp",
    title: "Ant-Man and the Wasp",
    aliases: ["ant man and the wasp", "antman wasp", "ant man wasp"],
    universe: "Marvel",
    mediaType: "movie",
    releaseYear: "2018",
    chronologyIndex: 185,
    releaseIndex: 185,
    canonStatus: "optional-canon",
    requiredBefore: [],
    optionalBefore: [],
    emotionalContext: "quantum hope and family rescue",
    continuityRelevance: "sets up the Quantum Realm mechanism that helps launch Endgame's time heist",
    importanceScore: 76,
    tmdbQuery: "Ant-Man and the Wasp",
  },
  {
    id: "loki-season-1",
    title: "Loki Season 1",
    aliases: ["loki", "loki season", "loki s1", "loki series"],
    universe: "Marvel",
    mediaType: "tv",
    releaseYear: "2021",
    chronologyIndex: 215,
    releaseIndex: 215,
    canonStatus: "canon",
    requiredBefore: ["avengers-endgame"],
    optionalBefore: [],
    emotionalContext: "identity rupture and multiverse awakening",
    continuityRelevance: "branches from Endgame's time-heist Loki and establishes TVA multiverse rules",
    importanceScore: 92,
    tmdbQuery: "Loki",
  },
  {
    id: "spider-man-far-from-home",
    title: "Spider-Man: Far From Home",
    aliases: ["far from home", "spider man far from home", "ffh"],
    universe: "Marvel",
    mediaType: "movie",
    releaseYear: "2019",
    chronologyIndex: 205,
    releaseIndex: 205,
    canonStatus: "canon",
    requiredBefore: ["spider-man-homecoming"],
    optionalBefore: [],
    emotionalContext: "post-Endgame grief",
    continuityRelevance: "directly triggers Peter's public identity crisis",
    importanceScore: 88,
    tmdbQuery: "Spider-Man: Far From Home",
  },
];

const dcEntries: CanonicalEntry[] = [
  {
    id: "batman-begins",
    title: "Batman Begins",
    aliases: ["batman begins", "dark knight origin"],
    universe: "DC",
    mediaType: "movie",
    releaseYear: "2005",
    chronologyIndex: 10,
    releaseIndex: 10,
    canonStatus: "canon",
    requiredBefore: [],
    optionalBefore: [],
    emotionalContext: "fear and origin",
    continuityRelevance: "establishes Nolan's Bruce Wayne and Gotham",
    importanceScore: 95,
    tmdbQuery: "Batman Begins",
  },
  {
    id: "the-dark-knight",
    title: "The Dark Knight",
    aliases: ["dark knight", "batman dark knight", "joker batman"],
    universe: "DC",
    mediaType: "movie",
    releaseYear: "2008",
    chronologyIndex: 20,
    releaseIndex: 20,
    canonStatus: "canon",
    requiredBefore: ["batman-begins"],
    optionalBefore: [],
    emotionalContext: "moral chaos",
    continuityRelevance: "continues Batman's escalation against Gotham's criminal order",
    importanceScore: 100,
    tmdbQuery: "The Dark Knight",
  },
  {
    id: "the-dark-knight-rises",
    title: "The Dark Knight Rises",
    aliases: ["dark knight rises", "batman rises"],
    universe: "DC",
    mediaType: "movie",
    releaseYear: "2012",
    chronologyIndex: 30,
    releaseIndex: 30,
    canonStatus: "canon",
    requiredBefore: ["the-dark-knight"],
    optionalBefore: [],
    emotionalContext: "legacy and rebirth",
    continuityRelevance: "concludes Nolan's Batman continuity",
    importanceScore: 96,
    tmdbQuery: "The Dark Knight Rises",
  },
];

const starWarsEntries: CanonicalEntry[] = [
  {
    id: "star-wars-a-new-hope",
    title: "Star Wars: A New Hope",
    aliases: ["a new hope", "star wars episode 4", "episode iv"],
    universe: "Star Wars",
    mediaType: "movie",
    releaseYear: "1977",
    chronologyIndex: 40,
    releaseIndex: 10,
    canonStatus: "canon",
    requiredBefore: [],
    optionalBefore: [],
    emotionalContext: "mythic calling",
    continuityRelevance: "introduces Luke, Leia, Vader, and the Rebellion",
    importanceScore: 94,
    tmdbQuery: "Star Wars",
  },
  {
    id: "the-empire-strikes-back",
    title: "Star Wars: The Empire Strikes Back",
    aliases: ["empire strikes back", "episode v", "star wars episode 5"],
    universe: "Star Wars",
    mediaType: "movie",
    releaseYear: "1980",
    chronologyIndex: 50,
    releaseIndex: 20,
    canonStatus: "canon",
    requiredBefore: ["star-wars-a-new-hope"],
    optionalBefore: [],
    emotionalContext: "loss and revelation",
    continuityRelevance: "deepens the Force and Skywalker lineage",
    importanceScore: 98,
    tmdbQuery: "The Empire Strikes Back",
  },
  {
    id: "return-of-the-jedi",
    title: "Star Wars: Return of the Jedi",
    aliases: ["return of the jedi", "episode vi", "star wars episode 6"],
    universe: "Star Wars",
    mediaType: "movie",
    releaseYear: "1983",
    chronologyIndex: 60,
    releaseIndex: 30,
    canonStatus: "canon",
    requiredBefore: ["the-empire-strikes-back"],
    optionalBefore: [],
    emotionalContext: "redemption and victory",
    continuityRelevance: "resolves Luke and Vader's original trilogy arc",
    importanceScore: 96,
    tmdbQuery: "Return of the Jedi",
  },
  {
    id: "ahsoka",
    title: "Ahsoka",
    aliases: ["ahsoka tano", "ahsoka series"],
    universe: "Star Wars",
    mediaType: "tv",
    releaseYear: "2023",
    chronologyIndex: 95,
    releaseIndex: 95,
    canonStatus: "canon",
    requiredBefore: ["return-of-the-jedi"],
    optionalBefore: ["the-mandalorian"],
    emotionalContext: "legacy and exile",
    continuityRelevance: "continues post-Empire Force mythology",
    importanceScore: 86,
    tmdbQuery: "Ahsoka",
  },
  {
    id: "the-mandalorian",
    title: "The Mandalorian",
    aliases: ["mandalorian", "mando"],
    universe: "Star Wars",
    mediaType: "tv",
    releaseYear: "2019",
    chronologyIndex: 90,
    releaseIndex: 90,
    canonStatus: "canon",
    requiredBefore: [],
    optionalBefore: [],
    emotionalContext: "found family",
    continuityRelevance: "sets the post-Return of the Jedi streaming-era world",
    importanceScore: 78,
    tmdbQuery: "The Mandalorian",
  },
];

const animeEntries: CanonicalEntry[] = [
  {
    id: "naruto",
    title: "Naruto",
    aliases: ["naruto original", "naruto part 1"],
    universe: "Naruto",
    mediaType: "anime",
    releaseYear: "2002",
    chronologyIndex: 10,
    releaseIndex: 10,
    canonStatus: "canon",
    requiredBefore: [],
    optionalBefore: [],
    emotionalContext: "loneliness and ambition",
    continuityRelevance: "establishes Naruto, Sasuke, Team 7, and village politics",
    importanceScore: 96,
    tmdbQuery: "Naruto",
  },
  {
    id: "naruto-shippuden",
    title: "Naruto Shippuden",
    aliases: ["shippuden", "naruto shippuden"],
    universe: "Naruto",
    mediaType: "anime",
    releaseYear: "2007",
    chronologyIndex: 20,
    releaseIndex: 20,
    canonStatus: "canon",
    requiredBefore: ["naruto"],
    optionalBefore: [],
    emotionalContext: "growth and loss",
    continuityRelevance: "continues the main shinobi conflict after the time skip",
    importanceScore: 98,
    tmdbQuery: "Naruto Shippūden",
  },
  {
    id: "naruto-pain-arc",
    title: "Naruto Shippuden: Pain Arc",
    aliases: ["naruto pain arc", "pain arc", "pain invasion", "pain assault"],
    universe: "Naruto",
    mediaType: "arc",
    releaseYear: "2010",
    chronologyIndex: 30,
    releaseIndex: 30,
    canonStatus: "canon",
    requiredBefore: ["naruto", "naruto-shippuden"],
    optionalBefore: [],
    emotionalContext: "grief, ideology, and forgiveness",
    continuityRelevance: "defines Naruto's philosophy before later war arcs",
    importanceScore: 100,
    tmdbQuery: "Naruto Shippūden",
  },
  {
    id: "boruto",
    title: "Boruto: Naruto Next Generations",
    aliases: ["boruto", "boruto anime"],
    universe: "Naruto",
    mediaType: "anime",
    releaseYear: "2017",
    chronologyIndex: 80,
    releaseIndex: 80,
    canonStatus: "canon",
    requiredBefore: ["naruto", "naruto-shippuden"],
    optionalBefore: ["naruto-pain-arc"],
    emotionalContext: "legacy generation",
    continuityRelevance: "continues the shinobi world through Naruto's son",
    importanceScore: 90,
    tmdbQuery: "Boruto: Naruto Next Generations",
  },
];

export const CANONICAL_UNIVERSES: CanonicalUniverse[] = [
  {
    id: "marvel",
    name: "Marvel",
    aliases: ["mcu", "marvel cinematic universe", "marvel netflix"],
    entries: marvelEntries,
  },
  {
    id: "dc",
    name: "DC",
    aliases: ["dc comics", "dc universe", "batman"],
    entries: dcEntries,
  },
  {
    id: "star-wars",
    name: "Star Wars",
    aliases: ["starwars", "jedi", "sith"],
    entries: starWarsEntries,
  },
  {
    id: "naruto",
    name: "Naruto",
    aliases: ["anime", "naruto universe", "shinobi"],
    entries: animeEntries,
  },
];

export const getAllCanonicalEntries = () =>
  CANONICAL_UNIVERSES.flatMap((universe) => universe.entries);

export const getCanonicalEntryById = (id: string) =>
  getAllCanonicalEntries().find((entry) => entry.id === id);

export const getCanonicalUniverseByName = (name: string) =>
  CANONICAL_UNIVERSES.find((universe) => universe.name === name);
